name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-code-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading source code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Print directory
        run: |
          ls -lrt
      - name: Install dependencies
        run: npm install
      - name: Running all test case
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Print directory
        run: |
          ls -lrt
      - name: Installing Surge
        run: npm install -g surge
      - name: Deploy to Staging
        run: surge --project ./dist --domain http://important-reading.surge.sh/
        env:
          SURGE_LOGIN: ragupsgtech29@gmail.com
          SURGE_TOKEN: a4e6d69a325f27b7af7636f7f0d87df1
