name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check directory & print in-build environment values
        run: |
          pwd
          ls -lrt
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: Cloning our source code here
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Printing directory
        run: |
          pwd
          ls -a
          ls -lrt
          git branch
      - name: Installing dependency
        run: npm install
      - name: Running test case
        run: |
          npm test
  deploy-code-cloud:
    runs-on: ubuntu-latest
    # needs: ci
    steps:
      - name: Downloading source code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Print directory
        run: |
          ls -lrt
      - name: Install dependencies
        run: npm install
      - name: Running all test case
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Print directory
        run: |
          ls -lrt
      - name: Installing Surge
        run: sudo npm install -g surge
      - name: Deploy to Staging
        run: surge --project ./dist/my-first-project --domain ${{ secrets.SURGE_URL }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
