name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-code-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading source code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Print directory
        run: |
          ls -lrt
      - name: Install dependencies
        run: npm install
      - name: Running all test case
        run: npm test
      - name: Build Project
        run: ng build --prod
      - name: Print directory
        run: |
          ls -lrt
