name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-code-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading source code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Print directory
