name: Sample GIthub Action workflow

on: [push]

jobs:
  sample-github-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing steps name
        run: echo "Welcome all"
  checkout-github-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check directory & print in-build environment values
        run: |  
          pwd
          ls -lrt
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"


